### PR TITLE
fix(theme-tasks): update liferay-frontend-theme-styled, liferay-front…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…end-theme-unstyled and liferay-font-awesome version reference

### CODE REVIEW

**Comment by izaera** [comment]
Didn't we agree time ago to not update these version numbers? :thinking: 

See this comment, for clay -> https://github.com/liferay/liferay-frontend-projects/issues/513#issuecomment-828502826

And this -> https://github.com/liferay/liferay-frontend-projects/issues/516 for the full context

@bryceosterhaus Any thoughts?

**Comment by bryceosterhaus** [comment]
@izaera I also remember deciding not to update these versions.

@georgel-pop-lr what is the reason for updating them? Is there a specific LPS or something that is depending on this?


I really don't have many opinions with the theme stuff so at the end of the day, if it is absolutely necessary then I have no problem updating them.

**Comment by georgel-pop-lr** [comment]
> @izaera I also remember deciding not to update these versions.
> 
> @georgel-pop-lr what is the reason for updating them? Is there a specific LPS or something that is depending on this?
> 
> I really don't have many opinions with the theme stuff so at the end of the day, if it is absolutely necessary then I have no problem updating them.

Hi @bryceosterhaus @izaera,

We have made lots of accessibility fixes in these versions, and I see many clients opening tickets and needing to ask them to upgrade the themes, so I guess it is better if our clients starts with a newer version, and maybe we have fewer tickets of this type.

Regards.

**Comment by izaera** [comment]
> We have made lots of accessibility fixes in these versions, and I see many clients opening tickets and needing to ask them to upgrade the themes, so I guess it is better if our clients starts with a newer version, and maybe we have fewer tickets of this type.

Apparently, that's aligned with the Dave Truong's comment I linked above...

Whatever is better. If updating the numbers leads to less support load, then let's update them. In the end it's the user responsibility to put the correct number so we can provide the defaults that lead to less friction.

**Review by izaera — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
sounds good to me! thanks for the explanation @georgel-pop-lr

**Comment by bryceosterhaus** [comment]
I'll release a new version first thing in the morning

**Comment by bryceosterhaus** [comment]
Screen Shot 2022-07-14 at 3 47 24 PM


is github stalking me? 😨

**Comment by bryceosterhaus** [comment]
released https://github.com/liferay/liferay-frontend-projects/releases/tag/liferay-theme-tasks%2Fv11.4.0

**Pull request merged**
