### PR TITLE
fix(js-themes-toolkit): npm package for liferay-frontend-theme-* needs to be updated due to InvalidReferenceException error for undefined variable reference (#513)

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay,

Attached is an update for https://issues.liferay.com/browse/IFI-2450.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by izaera** [comment]
Not sure if the change is correct because it really depends on the lifecycle of themes, which I really don't know... Let me check.

**Comment by izaera** [comment]
Note that, if this PR is finally approved, we also need to add the same changes to the v10 series: https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js

We need to maintain [three branches of the themes toolkit](https://github.com/liferay/liferay-frontend-projects#liferay-themes-toolkit). We tried to create 6-7 more branches but couldn't find any reason to support that, so we had to restrict ourselves to just 3. But hey, it is still funny with only three :tada:

**Comment by jonmak08** [comment]
> Note that, if this PR is finally approved, we also need to add the same changes to the v10 series: https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js

Yes, those changes have been made at https://github.com/liferay/liferay-frontend-projects/pull/514/commits/311fe9213b48831085f88d42d476102ef8a28da0#diff-dd6eee23873c5d1e8cc57932b48606e04b130366e44f6d007e03b188f305f01b

**Comment by jonmak08** [comment]
I updated this pull request with the changes mentioned by @pat270 in Slack.

> for 7.3 I want to say it's pretty safe defaulting to 5.0.20 (unstyled) and 5.0.15(styled)

**Comment by izaera** [comment]
> Yes, those changes have been made at 311fe92

True. In fact I saw the two files yesterday... :roll_eyes: 

LGTM. We can ship it

ship it

**Review by izaera — APPROVED** [review]

**Review by wincent — CHANGES_REQUESTED** [review]
I think this makes sense, but in order to keep the history clean (and avoid potentially confusing the changelog generator, which derives the logs from merge commits), can we rebase this and do it without the merge commit?

Screenshot 2021-04-29 -093457-8yfUNVqy@2x

Visually:

Screenshot 2021-04-29 -093844-ejHaE9HG@2x

**Comment by izaera** [comment]
This is already merged in master. Closing.

**Pull request closed without merging**
