### PR TITLE
fix(alloy-ui): AUI-3217 Fix accessibility issues in Image Viewer Component

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

There are 3 issues to fix:

1. Images without text alternative: This is addressed by passing image description in links object and then adding it to img element.
2. Empty headers: This is addressed by replacing wrong h4 and h5 elements by span with h4 and h5 css class.
3. Links with empty text: This is addressed by adding some text specific for screen readers.

Thanks.

Regards.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@antonio-ortega this looks good, my only question is what about localization? Or is it fine to just be english?

Also, do you need a new release of alloy after this is merged?

**Comment by antonio-ortega** [comment]
Hi @bryceosterhaus ,

I need a new release of AlloyUI after this is merged. I can update it in liferay-portal later on, I have already created LPS-172985 to include this update.

About localization, I thought about this but as far as I can remember you need to pass language keys to AlloyUI but having a look at [ImageViewer API](https://alloyui.com/api/classes/A.ImageViewer.html) I couldn't find a way to pass those keys to this component.

Thanks.

Regards.

**Comment by antonio-ortega** [comment]
Hey guys,

Could you have a look at this pull request, please?

Thanks!

**Comment by bryceosterhaus** [comment]
@antonio-ortega sorry for the delay. I will look today and get a release out as soon as possible

**Comment by antonio-ortega** [comment]
Thanks, @bryceosterhaus . I appreciate it!

**Pull request merged**
