### PR TITLE
feat(theme-tasks): update theme dependencies to match Liferay 7.4.13

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I pulled these version numbers from this release of Liferay portal, https://github.com/liferay/liferay-portal/commit/e64d3f8d5f0b61fe497d4728f1f2c878d8e589c1

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Would it be worth automating something here based on liferay-portal releases?

**Comment by izaera** [comment]
> Would it be worth automating something here based on liferay-portal releases?

Not sure if it can be done... Where can we get that information from? I already grab information from GH in my target platforms script (reading yarn.lock for example) and it's quite easy, so maybe we can do something similar for this...

**Comment by bryceosterhaus** [comment]
I was thinking we could possibly do a daily/weekly action to check the [tags on liferay-portal](https://github.com/liferay/liferay-portal/tags) and then if there is a new one, we start the publishing process or at minimum we could spawn a new issue on the repo.

**Comment by izaera** [comment]
I like the idea. We can use it to publish target platforms too.

Can create a GH action that executes daily to check for new tags? That way we can see the results in our mailbox. And also, in the future, we may grow it to make the publication automatic, if we find the way. Like we discussed [here](https://github.com/liferay/liferay-frontend-projects/issues/740#issuecomment-970891049).

**Pull request merged**
