### PR TITLE
feat(eslint-plugin): add one-var rule

### PR DESCRIPTION
**Pull request by kresimir-coko**
With the gentle nudge by @nhpatt I ended up testing and using the [one-var](https://eslint.org/docs/rules/one-var) rule with the `['error', 'never']` settings. I have tested it inside `liferay-portal` and it produces 72 autofixable errors.

~~I found this [one-var-declaration-per-line](https://eslint.org/docs/rules/one-var-declaration-per-line) ESLint rule. When I plugged it in `liferay-portal` it produced 63 errors, all of which are auto-fixable. The autofix is weird as it just pushes the vars to a new line. The autofix issue can be seen in the 2nd commit.~~

### CODE REVIEW

**Comment by nhpatt** [comment]
Did is not what we want, AFAIK. I would say that this is closer: https://eslint.org/docs/rules/one-var

**Comment by kresimir-coko** [comment]
> Did is not what we want, AFAIK. I would say that this is closer: https://eslint.org/docs/rules/one-var

@nhpatt that crossed my mind, I'll check it out as their docs are unclear, but I thought that we want to declare variables when they're about to be used, not at the start of the function, and as I'm reading this rule, it lints against that. For example this is incorrect code: 
```js
function foo(){
    const bar = false;
    const baz = true;
    let qux;
    let norf;
}
```
But, this is correct code:
```js
function foo(){
    const bar = true,
        baz = false;
    let qux,
        norf;
}
```
I've never seen us comma-separate variable declarations.

**Comment by nhpatt** [comment]
> I thought that we want to declare variables when they're about to be used, not at the start of the function

Yep, that's what we want

> I've never seen us comma-separate variable declarations.

I saw that there are some flags that disallow that and force you to use var/let several times

**Comment by kresimir-coko** [comment]
You were right @nhpatt, sorry for doubting you Sensei.

**Comment by kresimir-coko** [comment]
I've force pushed the new rule @nhpatt, thanks for the feedback

**Comment by bryceosterhaus** [comment]
LGTM!

**Pull request merged**
