### PR TITLE
feat(npm-scripts)!: enforce use of `@liferay/` named scope

### PR DESCRIPTION
**Pull request by wincent**
Ideally we'd have renamed all the packages (as part of [LPS-129670](https://issues.liferay.com/browse/LPS-129670)), but that is going to be a huge task that we are not likely to get to in a hurry (especially because in order to be complete we'd have to do it on multiple branches). So in this commit, we're taking the "allow list" approach, which means banning every package name that isn't in the named scope _except_ some pre-set list of exceptions containing some 200 odd names that currently exist in our repos/branches and that we own and therefore consider to be relatively safe with respect to [dependency confusion attacks](https://github.com/liferay/liferay-frontend-projects/blob/314d612abaea193d26b0f4c496e65bc5228c2882/guidelines/general/security/dependency_confusion.md).

The names come from [this spreadsheet](https://docs.google.com/spreadsheets/d/1jXsn5ldB6IehQTsnggWHJKNdo-1m1Mmuoc26lh12saU/edit) which we prepared a couple of months ago, so it may be out of date. My test plan should catch any omissions that have snuck into liferay-portal in the meantime.

**Test plan:** Copy files over to liferay-portal repo and run `yarn checkFormat` from the top. See no errors reported. Edit a package name and retry. See errors reported.

Closes: https://github.com/liferay/liferay-frontend-projects/issues/469

### CODE REVIEW

**Comment by wincent** [comment]
Geez. It's a bit worse than I thought it would be...

```
apps/click-to-chat/click-to-chat-web/package.json: BAD - package name click-to-chat-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/commerce/commerce-theme-minium/commerce-theme-minium/package.json: BAD - package name minium-theme should be under @liferay/ named scope - https://git.io/JOgy7
apps/commerce/commerce-theme-speedwell/commerce-theme-speedwell/package.json: BAD - package name speedwell-theme should be under @liferay/ named scope - https://git.io/JOgy7
apps/dynamic-data-mapping/dynamic-data-mapping-data-provider-web/package.json: BAD - package name dynamic-data-mapping-data-provider-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/expando/expando-web/package.json: BAD - package name expando-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/frontend-taglib/frontend-taglib-clay-test-alert-toast-sample-web/package.json: BAD - package name frontend-taglib-clay-test-alert-toast-sample-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/frontend-theme/frontend-theme-styled/package.json: BAD - package name liferay-frontend-theme-styled should be under @liferay/ named scope - https://git.io/JOgy7
apps/frontend-theme/frontend-theme-unstyled/package.json: BAD - package name liferay-frontend-theme-unstyled should be under @liferay/ named scope - https://git.io/JOgy7
apps/knowledge-base/knowledge-base-web/package.json: BAD - package name knowledge-base-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/layout/layout-reports-web/package.json: BAD - package name layout-reports-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/layout/layout-set-prototype-web/package.json: BAD - package name layout-set-prototype-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/map/map-common/package.json: BAD - package name map-common should be under @liferay/ named scope - https://git.io/JOgy7
apps/my-subscriptions/my-subscriptions-web/package.json: BAD - package name my-subscriptions-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/notifications/notifications-web/package.json: BAD - package name notifications-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/oauth2-provider/oauth2-provider-web/package.json: BAD - package name oauth2-provider-web should be under @liferay/ named scope - https://git.io/JOgy7
apps/user-groups-admin/user-groups-admin-web/package.json: BAD - package name user-groups-admin-web should be under @liferay/ named scope - https://git.io/JOgy7
```

**Comment by jbalsas** [comment]
All those crept in since we last went through the security sweep? 

Many make sense, but I wonder what happened with the `theme` ones, both `comemrce` and ours.. 🤔

**Comment by jbalsas** [comment]
Also particularly telling is `apps/knowledge-base/knowledge-base-web` which is older than myself as far as I can tell, so my best guess is that we just recently added a `package.json` to them, even though the modules were already there... 🤷

**Comment by wincent** [comment]
Yeah, the theme ones I think slipped through because:

- We have `liferay-frontend-theme-styled` but not `frontend-theme-styled`
- Ditto for `liferay-frontend-theme-unstyled` and `frontend-theme-unstyled`

The commerce ones are a similar story:

- Module is called `commerce-theme-minimum` but we have a registered package called `minium-theme`
- Module is called `commerce-theme-speedwell` but we have a registered package called `minium-speedwell`

So yeah, adjusting for those, 12 new packages (or new `package.json` in those packages, as is the case with `knowledge-base-web`)...

**Comment by wincent** [comment]
Ok, in a comedy of errors, I published 4 packages too many:

```
click-to-chat-web
Status: 0
minium-theme
Status: 0
speedwell-theme
Status: 0
dynamic-data-mapping-data-provider-web
Status: 0
expando-web
Status: 0
frontend-taglib-clay-test-alert-toast-sample-web
Status: 0
liferay-frontend-theme-styled
Status: 0
liferay-frontend-theme-unstyled
Status: 0
knowledge-base-web
Status: 0
layout-reports-web
Status: 0
layout-set-prototype-web
Status: 0
my-subscriptions-web
Status: 0
notifications-web
Status: 0
oauth2-provider-web
Status: 0
user-groups-admin-web
Status: 0
```

Due to my silliness of copy-pasting the entire list instead of omitting the theme packages. This means the four legit theme packages got new `@latest` versions that are just placeholders. 🤦 

So, to fix that, can't unpublish `liferay-frontend-theme-{un,}styled` because:

```
npm ERR! You can no longer unpublish this package.
npm ERR! Failed criteria:
npm ERR! has dependent packages in the registry
npm ERR!
npm ERR! Please deprecate it instead:
npm ERR! npm deprecate -f 'liferay-frontend-theme-styled@6.0.1' "this package has been deprecated"
```

Deprecating instead:

```
npm deprecate -f 'liferay-frontend-theme-styled@6.0.1' "6.0.1 is a deprecated placeholder package; please use a different version"
npm deprecate -f 'liferay-frontend-theme-unstyled@6.0.1' "6.0.1 is a deprecated placeholder package; please use a different version"
```

And for the commerce themes, this worked fine:

```
npm unpublish speedwell-theme@4.0.1
npm unpublish minium-theme@5.0.1 
```

Proof:

- With deprecation notices:
  - https://www.npmjs.com/package/liferay-frontend-theme-styled/v/6.0.1
  - https://www.npmjs.com/package/liferay-frontend-theme-unstyled/v/6.0.1
- Other versions, no deprecation notices:
  - https://www.npmjs.com/package/liferay-frontend-theme-styled/v/6.0.0
  - https://www.npmjs.com/package/liferay-frontend-theme-unstyled/v/6.0.0
- Unpublished versions not in the list:
  - https://www.npmjs.com/package/minium-theme?activeTab=versions
  - https://www.npmjs.com/package/speedwell-theme?activeTab=versions

Here's the script I used for publishing, with the bogus lines commented out:

```js
#!/usr/bin/env node

const child_process = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

function publish(packageJSON, name) {
        const dirname = path.dirname(packageJSON);
        const {version} = JSON.parse(fs.readFileSync(packageJSON, 'utf8'));

        const dxp = dirname.startsWith('dxp/');

        const json = JSON.stringify({
                        name,
                        version: version ? version : '0.0.1',
                        license: dxp ? 'SEE LICENSE IN https://github.com/liferay/liferay-portal/blob/master/modules/dxp/copyright.js' : 'GPL',
                        scripts: {
                                preinstall: `echo "This package is not intended to be consumed directly; please see https://github.com/liferay/liferay-portal/blob/master/modules/${dirname}"; exit 1`,
                        }
                },
                null,
                2
        );

        const scratch = path.join(
                os.tmpdir(),
                fs.mkdtempSync('register'),
        );

        fs.mkdirSync(scratch);

        const cwd = process.cwd();

        process.chdir(scratch);

        fs.writeFileSync('package.json', json, 'utf8');

        fs.writeFileSync('README.md',
                `# ${name}\n` +
                `\n` +
                `This package is not intended to be consumed directly; please see https://github.com/liferay/liferay-portal/blob/master/modules/${dirname}\n`,
                'utf8');

        console.log(name);

        const {status} = child_process.spawnSync('npm', ['publish']);

        console.log(`Status: ${status}`);

        if (status) {
                process.exit(status);
        }

        process.chdir(cwd);
}

publish('apps/click-to-chat/click-to-chat-web/package.json', 'click-to-chat-web');

// Bogus.

// publish('apps/commerce/commerce-theme-minium/commerce-theme-minium/package.json', 'minium-theme');
// publish('apps/commerce/commerce-theme-speedwell/commerce-theme-speedwell/package.json', 'speedwell-theme');

publish('apps/dynamic-data-mapping/dynamic-data-mapping-data-provider-web/package.json', 'dynamic-data-mapping-data-provider-web');
publish('apps/expando/expando-web/package.json', 'expando-web');
publish('apps/frontend-taglib/frontend-taglib-clay-test-alert-toast-sample-web/package.json', 'frontend-taglib-clay-test-alert-toast-sample-web');

// Bogus.

// publish('apps/frontend-theme/frontend-theme-styled/package.json', 'liferay-frontend-theme-styled');
// publish('apps/frontend-theme/frontend-theme-unstyled/package.json', 'liferay-frontend-theme-unstyled');

publish('apps/knowledge-base/knowledge-base-web/package.json', 'knowledge-base-web');
publish('apps/layout/layout-reports-web/package.json', 'layout-reports-web');
publish('apps/layout/layout-set-prototype-web/package.json', 'layout-set-prototype-web');

// Can't publish this one because it is not ours:

// publish('apps/map/map-common/package.json', 'map-common');

publish('apps/my-subscriptions/my-subscriptions-web/package.json', 'my-subscriptions-web');
publish('apps/notifications/notifications-web/package.json', 'notifications-web');
publish('apps/oauth2-provider/oauth2-provider-web/package.json', 'oauth2-provider-web');
publish('apps/user-groups-admin/user-groups-admin-web/package.json', 'user-groups-admin-web');
```

Next steps:

1. Merge this PR.
2. Cut release.
3. Integrate in liferay-portal.
4. Bump theme version numbers (patch version) there so that next attempt to release will actually work (ie. otherwise, numbers would clash).

**Pull request merged**
