### PR TITLE
fix(js-toolkit): fix security vulnerability related to dot-prop and merge

### LINKED ISSUE #571: Dependency vulnerability Fix Request - dot-prop and merge
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [x] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description
Dependabot alerted us to two high severity vulnerabilities related to the `liferay-npm-bundler` and the `dot-prop` and `merge` dependencies. The bundler is currently used as a dev dependency so I am wondering if these issues are even relevant in the context of the frontend. If someone could confirm this, that would be great!

dot-prop info:
- Path: `liferay-npm-bundler > insight > conf > dot-prop`
- More info: `https://npmjs.com/advisories/1213`

merge info:
- Path: `liferay-npm-bundler > liferay-npm-build-tools-common > merge`
- More info: `https://npmjs.com/advisories/1666`

**Desired behavior:**
Resolve high severity vulnerabilities 

**Current behavior:**
npm audits result in a couple high severity vulnerabilities 

**Repro instructions (if applicable):**
`npm audit`

**Other information (environment, versions etc):**
We are currently using version 2 of the npm bundler.

### PR DESCRIPTION
**Pull request by izaera**
Closes #571

### CODE REVIEW

**Comment by izaera** [comment]
I've rebashed and pushed the new yarn.lock. I think everything makes sense, but since you saw strange things in the `yarn.lock`, @bryceosterhaus , can you check if it is OK now?

Keep in mind that we [removed this devDependency](https://github.com/liferay/liferay-frontend-projects/pull/582/commits/5b94d4e02eea509e5432cd2e62a248b44f1a65b6#diff-7d1290f849eaf5903d84aa37b820c6dd7bda4ed795c4412884c638f50a83d84fL26-L28) which was incorrect. That is causing the removal of some of the `liferay-npm-*` dependencies.

**Review by bryceosterhaus — APPROVED** [review]
👍  looks good. I think I initially mistook the yarn.lock to be out root level one and not at the `js-toolkit/` level

**Comment by izaera** [comment]
> I think I initially mistook the yarn.lock to be our root level one and not at the js-toolkit/ level

Ah, yes. I had serious problems with that during the making of this PR :roll_eyes: (several times)

**Comment by izaera** [comment]
So, I'm merging this but won't release any version since it is low priority and nobody has really requested it explicitly. Will be included in the next release.

**Pull request merged**
