### PR TITLE
feat(npm-scripts): add support for multiple entry points

### PR DESCRIPTION
**Pull request by bryceosterhaus**
cc @izaera let me know what you think about this, it seems to work fine locally for me

### CODE REVIEW

**Review by izaera — APPROVED** [review]
LGTM. 
However, I would move the logic to test for Array to the place where the config is read, then assume that it is always an array in the other places, where you consume the data. That would save you a lot of code :+1:

**Comment by bryceosterhaus** [comment]
@izaera good idea, I moved it to our `normalizeNpmscriptsConfig` util

**Comment by izaera** [comment]
So, LGTM again :sweat_smile:

**Comment by bryceosterhaus** [comment]
gonna test again tomorrow and release if it works as expected

**Pull request merged**
