### PR TITLE
chore: add git ignore .idea files

### PR DESCRIPTION
**Pull request by georgel-pop-lr**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Adding the gulp script is a little odd at first glance... But I guess not necessarily wrong. 🤷

**Comment by georgel-pop-lr** [comment]
> Adding the gulp script is a little odd at first glance... But I guess not necessarily wrong. shrug
Hi, 

I agree but is very useful, I always added it myself by hand but I guess if people see it there they would use it.

Regards.

**Comment by izaera** [comment]
@georgel-pop-lr you can achieve the same functionality by running `npx gulp` in the project folder (without having to install the package globally)

**Comment by izaera** [comment]
Also, I think that `./node_modules/bin/...` thing may fail in Windows

**Comment by georgel-pop-lr** [comment]
> And in some circumstances, it will also fail if yarn hoists it.
> 
> TBH, I would send a follow-up to change that to either remove the script or use:
> 
> ```json
> "scripts": {
>      "gulp": "npx gulp"
> }
> ```
> 
> Or even better:
> 
> ```json
> "scripts": {
>      "gulp": "gulp"
> }
> ```
> 
> I think that works too and doesn't fail under yarn or windows scenarios.

Thanks for your suggestios: https://github.com/liferay/liferay-frontend-projects/pull/1112

**Pull request merged**
