### PR TITLE
chore(npm-scripts): Update @testing-library/react and  @testing-library/dom

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Review by kresimir-coko — APPROVED** [review]
I don't see anything wrong with these, they look like big version upgrades so not sure how DXP will react to it. Have you tested these changes in DXP?

**Comment by victorg1991** [comment]
Yes @kresimir-coko I had to update a bunch of modules to work with these versions: https://github.com/liferay-frontend/liferay-portal/pull/1771 there were 245 failing tests 😅

**Comment by victorg1991** [comment]
Rebased with master and added the `!`to denote the breaking change :)

**Comment by victorg1991** [comment]
I'm going to merge this and cut a new release

**Pull request merged**
