### PR TITLE
feat(liferay-cli): add new published target platforms

### PR DESCRIPTION
**Pull request by izaera**
This adds the target platforms I published yesterday to the list of available targets when `liferay new <project>` is run.

Right now I'm showing this menu:

imagen

I would like to find a more descriptive names, but that's all I could think of.

The main idea we need to convey is that by using a target platform for a specific version you get access to all our APIs through bundler-imports whereas choosing `portal-agnostic` (the `Liferay Portal CE (not using platform's APIs)` you don't. Sadly, expressing that intuitively, and in one line, seems very difficult to me.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
I think the way you have it is fine for now. I think it would be rare for someone to use the portal-agnostic one. If we need to provide further docs, we could link back to our README or something to give more info.

**Comment by izaera** [comment]
> we could link back to our README or something to give more info.

I like that. I will add some way to show the documentation in liferay-cli :+1: (probably printing a link to begin with, but we may open a browser in the future, for example. Or even provide text documentation similar to the one provided by `man`...

**Comment by izaera** [comment]
I've added https://github.com/liferay/liferay-frontend-projects/pull/756/commits/77702f42fb0edaa5abf6cd8b99b1e87601e5409d that prints the link to the docs, like this:

imagen

I think it's OK as a first step towards something more powerful. I'm thinking in something like this, that I saw yesterday, from Rust: 

imagen

Rust has its own package manager named `cargo`, which has a command `doc` that opens the relevant documentation for any project. We wouldn't be able to do it because there's no official way to generate documentation for npm packages, but we can be inspired by it to create a good documentation tool for our JS Toolkit, I think...

**Comment by izaera** [comment]
I'll defer merging this until I get some opinions on the `liferay docs` command (if it is OK to keep it or we prefer not to ship it yet). 

Since I need to prepare more PRs to make the switch from yeoman generator to liferay-cli happen, there's no need to rush.

**Comment by bryceosterhaus** [comment]
@izaera I think thats a great starting point, just having a reference is helpful. Instead of a separate command of `docs` entirely, can we just add that info to `--help`? That way it might be a bit more findable, I don't know if I have ever seen a `docs` command before.

**Comment by izaera** [comment]
:thinking: I don't think we can use `--help` because that's used by `yargs` to describe the usage of the tool (commands and switches).

Nevertheless, the command is very discoverable, IMO, because if you run `liferay` alone (or `liferay --help`) you get this:

imagen

So, there you have the `liferay docs`...

Also, the good thing about having a real command is that we can then implements things like `liferay docs search bundling`, `liferay docs search adapting`, or `liferay docs open online`, etc. to access different parts of the documentation (something similar to `man` and `apropos` in linux systems...).

**Comment by bryceosterhaus** [comment]
Ah I see, I forgot it was built into yargs. That sounds good to me then!

**Comment by izaera** [comment]
Merging this to reduce the PR queue, since it is approved.

**Pull request merged**
