### PR TITLE
docs: add a table with links to per-project and per-package issue listings

### PR DESCRIPTION
**Pull request by wincent**
With more projects in the monorepo we need good tools for dealing with the increased load on the issue tracker, so that people can focus on what they need to on any given moment.

### CODE REVIEW

**Comment by wincent** [comment]
Whoops: link text is wrong — going to force push to update.

**Comment by jbalsas** [comment]
> Whoops: link text is wrong — going to force push to update.
 
dissapointment

**Comment by jbalsas** [comment]
Would be nice to also have issue templates that can target the different projects?

Not sure if we can have hierarchies, so we can have:

- Project A
    - Bug
    - Feature Request
- Project B
    - Conversation
    - Question

Main benefit of at least the root level would be to automatically provide project labels which I guess are out of the scope of our amazin labeller action ;)

**Comment by wincent** [comment]
Yes, I think issue templates are a good idea. I was going to look at those when I bring in a project that actually already has them, but we can do it for these two projects that we already have (I'll make that a separate PR).

**Comment by wincent** [comment]
Initial sketch of templates here: https://github.com/liferay/liferay-frontend-projects/pull/76

**Comment by wincent** [comment]
Gonna merge this. Too lazy to find a gif.

lazy

**Pull request merged**
