### PR TITLE
fix(js-toolkit): support scoped packages when building JAR files

### LINKED ISSUE #446: JS Toolkit is failing to make JAR files for scoped packages
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description
Currently the JS Toolkit is failing to make JAR files for scoped packages.

**Desired behavior:**
I would like it to work correctly if it's possible.

**Current behavior:**
Currently it fails.

This is the exact error:

```
> lnbs-copy-assets
Project assets copied.
Error: ENOENT: no such file or directory, open 'dist/@XXXXX/XXXXX-1.0.0.jar'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at zip.generateAsync.then (/Users/XXXXX/node_modules/liferay-npm-bundler/lib/jar/index.js:58:28)
```

Some parts have been replaced by `XXXXX` to protect the innocents.

**Repro instructions (if applicable):**
Simply create a project and give it a npm scoped package name. Something along the lines of `@my-scope/project`.

**Other information (environment, versions etc):**
I don't have more information, sorry.

### PR DESCRIPTION
**Pull request by izaera**
Tested locally with a scoped project.

Closes #446

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM. Would it be possible to add a quick and simple unit test for this? Just to give some sanity to see it work with both scoped and non-scoped packages.

**Comment by izaera** [comment]
>  quick and simple...

Nope if it needs to be quick and simple :sweat_smile: 

I will have a look at this, but I usually discarded tests related to packaging and bundling because you need a lot of fixtures in-place and they take long (it's more an integration than a unit test). 

My initial idea was to leave these things to the QA side, but we never got to have a real working QA suite of tests (other than what he have at the [qa folder](https://github.com/liferay/liferay-frontend-projects/tree/master/maintenance/projects/js-toolkit/qa), which are simple smoke tests of each type of portlet).

So I'll see if I can add an isolated test for this, but we need to decide some strategy for the future. The lack of proper QA testing in this project has always been a problem and, though there are things that can be unit tested, in the end we need another layer of integration tests to make sure all pieces fit together...

**Comment by izaera** [comment]
Turns out I lied ¯\_(ツ)_/¯ (see my new commit with the test) 
 
lied

**Comment by bryceosterhaus** [comment]
>  I usually discarded tests related to packaging and bundling because you need a lot of fixtures in-place

That is totally fine and I agree, having to add tons of fixtures for tests is a major headache and which is why I asked if it might be simple and quick lol

Glad it was easy to add!

**Pull request merged**
