### PR TITLE
feat: run CI on Windows

### PR DESCRIPTION
**Pull request by wincent**
We'll see how performant this is. In the old repo, in Travis, Windows was dog slow. Let's see if it is fast enough as-is; if it isn't there are a number of Pro-Tips™ linked to in the related issues.

Seeing as I am splitting out the Windows test run (and on Windows we are only going to run tests, not format-checking and linting), I also split out the rest. We'll see if this improves or worsens the speed of feedback; we're running stuff in parallel (good), but each parallel job duplicates the work of checking out, running `yarn install` etc.

Closes: https://github.com/liferay/liferay-frontend-projects/issues/37

### CODE REVIEW

**Comment by wincent** [comment]
Results:

```
format-check (12.x)
succeeded now in 1m 19s

lint (12.x)
succeeded 1 minute ago in 1m 12s

test (12.x)
succeeded 42 seconds ago in 1m 31s

test-windows (12.x)
failed 2 minutes ago in 4m 33s
```

No surprises there... `yarn install` is mega-slow on Windows... going to see if [caching](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows) can be used to speed things up at all.

Also, going to look into the failure on Windows, which may be legit:

```
Summary of all failing tests
FAIL projects/npm-tools/packages/npm-scripts/test/scripts/theme.js
  ● scripts/theme.js › findModulesDirectory() › returns null when there is no "modules" ancestor

    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: "C:\\modules"

       98 | 
       99 | 		it('returns null when there is no "modules" ancestor', () => {
    > 100 | 			expect(findModulesDirectory(os.tmpdir())).toBe(null);
          | 			                                          ^
      101 | 		});
      102 | 
      103 | 		it('returns the path when there is an "modules" ancestor', () => {

      at Object.<anonymous> (test/scripts/theme.js:100:46)

  ● scripts/theme.js › prepareAdditionalBuildArgs() › complains if there is no "modules" ancestor

    expect(received).toThrow(expected)

    Expected pattern: /Unable to find "modules"/
    Received message: "Unable to find \"frontend-theme\" directory"

          68 | 	const themes = path.join(modules, 'apps/frontend-theme');
          69 | 	if (!fs.existsSync(themes)) {
        > 70 | 		throw new Error('Unable to find "frontend-theme" directory');
             | 		      ^
          71 | 	}
          72 | 
          73 | 	const args = [];

      68 | 	const themes = path.join(modules, 'apps/frontend-theme');
      69 | 	if (!fs.existsSync(themes)) {
    > 70 | 		throw new Error('Unable to find "frontend-theme" directory');
         | 		      ^
      71 | 	}
      72 | 
      73 | 	const args = [];

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      at prepareAdditionalBuildArgs (src/scripts/theme.js:70:9)
      at test/scripts/theme.js:118:17
      at Object.<anonymous> (test/scripts/theme.js:118:47)
      at Object.<anonymous> (test/scripts/theme.js:118:47)

  ● scripts/theme.js › run() › build › complains if there is no "modules" ancestor

    expect(received).toThrow(expected)

    Expected pattern: /Unable to find "modules"/
    Received message: "Unable to find \"frontend-theme\" directory"

          68 | 	const themes = path.join(modules, 'apps/frontend-theme');
          69 | 	if (!fs.existsSync(themes)) {
        > 70 | 		throw new Error('Unable to find "frontend-theme" directory');
             | 		      ^
          71 | 	}
          72 | 
          73 | 	const args = [];

      68 | 	const themes = path.join(modules, 'apps/frontend-theme');
      69 | 	if (!fs.existsSync(themes)) {
    > 70 | 		throw new Error('Unable to find "frontend-theme" directory');
         | 		      ^
      71 | 	}
      72 | 
      73 | 	const args = [];

      at prepareAdditionalBuildArgs (src/scripts/theme.js:70:9)
      at run (src/scripts/theme.js:90:20)
      at test/scripts/theme.js:213:18
      at Object.<anonymous> (test/scripts/theme.js:213:32)
      at Object.<anonymous> (test/scripts/theme.js:213:32)

FAIL projects/npm-tools/packages/npm-scripts/test/utils/filterChangedFiles.js
  ● filterChangedFiles() › when LIFERAY_NPM_SCRIPTS_WORKING_BRANCH_NAME is set › returns only changed files, unless it detects a @liferay/npm-scripts update

    expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 1

    - Array [
    -   "code",
    - ]
    + Array []

      176 | 
      177 | 			git('checkout', '--detach', 'c');
    > 178 | 			expect(filterChangedFiles(files)).toEqual(['code']);
          | 			                                  ^
      179 | 
      180 | 			git('checkout', '--detach', 'd');
      181 | 			expect(filterChangedFiles(files)).toEqual(['code', 'package.json']);

      at Object.<anonymous> (test/utils/filterChangedFiles.js:178:38)


Test Suites: 2 failed, 65 passed, 67 total
Tests:       4 failed, 2 skipped, 1096 passed, 1102 total
Snapshots:   40 passed, 40 total
Time:        47.408 s
Ran all test suites in 3 projects.
```

**Comment by wincent** [comment]
Ok, so we'll see if this speeds things up on the second run. On this one, we have:

```
format-check (12.x)
failed 3 minutes ago in 1m 0s (was 1m 19s last time)

lint (12.x)
succeeded 2 minutes ago in 1m 46s (was 1m 12s last time)

test (12.x)
succeeded 2 minutes ago in 1m 45s (was 1m 31s last time)

test-windows (12.x)
failed 2 minutes ago in 3m 33s (was 4m33s last time)
```

That's good, as it shows that checking/saving to the cache didn't slow things down. The four jobs printed this output about the cache, respectively:

```
Cache not found for input keys: Linux-build-yarn-cache-eb266e408c689345842ad04688cc8cfbdd34117480f698f2ad44378f03a87035

Post job cleanup.
/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/liferay-frontend-projects/liferay-frontend-projects --files-from manifest.txt
Cache saved successfully

Post job cleanup.
Warning: reserveCache failed: Cache already exists. Scope: refs/pull/85/merge, Key: Linux-build-yarn-cache-eb266e408c689345842ad04688cc8cfbdd34117480f698f2ad44378f03a87035, Version: 5bc25161092f2c8bcc7218a166e6feb59fe5dd3e389258760f345aee7cfabadc

Cache not found for input keys: Windows-build-yarn-cache-ea7316d677b6d103044bdd56ddef9336ecd11c72ee8c62c1ae85077bfe157bc9
```

So:

- We see two "Cache not found" messages, which you'd expect, for the first Linux job and the first Windows job to try hitting the cache.
- We see one job successfully save the cache.
- We see one job with a mysterious "reserveCache failed: Cache already exists" message. Not sure what to maek of that one; maybe there is something racy going on because these jobs are running in parallel. This may be harmless (ie. the second job to try is just going to fail and not use the cache).

Going to push another commit now to see what happens on the second run.

**Comment by wincent** [comment]
Second run stats:

```
format-check (12.x)
failed 3 minutes ago in 1m 6s (was 1m 0s last time)

lint (12.x)
succeeded 2 minutes ago in 1m 0s (was 1m 46s last time)

test (12.x)
succeeded 2 minutes ago in 1m 22s (was 1m 45s last time)

test-windows (12.x)
failed 2 minutes ago in 3m 36s (was 3m 33s last time)
````

Not very scientific, but we see a speed-up on the first two jobs (and also they had cache hits). The other two jobs did not have cache hits, it would seem:

```
Run actions/cache@v2
Received 189761428 of 193955732 (97.8%), 180.8 MBs/sec
Received 193955732 of 193955732 (100.0%), 147.6 MBs/sec
Cache Size: ~185 MB (193955732 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e11e670f-7b31-4330-9eb6-7381016c4b64/cache.tzst -P -C /home/runner/work/liferay-frontend-projects/liferay-frontend-projects
Cache restored from key: Linux-build-yarn-cache-eb266e408c689345842ad04688cc8cfbdd34117480f698f2ad44378f03a87035

Run actions/cache@v2
Received 181372820 of 193955732 (93.5%), 172.8 MBs/sec
Received 193955732 of 193955732 (100.0%), 113.9 MBs/sec
Cache Size: ~185 MB (193955732 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/f72d559a-cd5d-4f97-a395-69b87e9940b6/cache.tzst -P -C /home/runner/work/liferay-frontend-projects/liferay-frontend-projects
Cache restored from key: Linux-build-yarn-cache-eb266e408c689345842ad04688cc8cfbdd34117480f698f2ad44378f03a87035

Post job cleanup.
Cache hit occurred on the primary key Linux-build-yarn-cache-eb266e408c689345842ad04688cc8cfbdd34117480f698f2ad44378f03a87035, not saving cache.

Run actions/cache@v2
Cache not found for input keys: Windows-build-yarn-cache-ea7316d677b6d103044bdd56ddef9336ecd11c72ee8c62c1ae85077bfe157bc9
```

- Not sure what "Cache hit occurred on the primary key" means, followed by "not saving cache"... it was like it was racing to save the cache and decided not to do it, but it says nothing about reading from the cache (the jobs that definitely read from the cache said "Cache restored from key").
- The Windows job did not have a cache hit, which is ironic, because that's the one we're actually trying to speed up here 😂.

**Comment by wincent** [comment]
Ok stuff I've think I've learned:

- I was misreading the output on some of those prior jobs. There are two parts, "Use or update Yarn cache" and "Post Use or update Yarn cache", and I wasn't looking at both in all cases. You can indeed seeing the cache being correctly saved and restored on Linux.
- I think the cache misses on Windows are due to the test failures; it doesn't save the cache unless the job succeeds; so once I fix the test failures, we should see the cache starting to work.
- My `console.log()`-ing shows that there really is a darn `C:\modules` directory on these hosts, which explains at least three of the failures — 🤦‍♂️ — so will either have to disable those tests or tweak the implementation to not just accept any old modules directory (ie. we might have to insist on there being a package.json in there too).

**Comment by jbalsas** [comment]
whatarewelookingat

**Comment by wincent** [comment]
My work here is done.

With the cache active, run on Windows is 3m 35s.

**Comment by wincent** [comment]
Ok, I didn't have time to test this fully (ie. make sure it's really only going to run against changed files), but I was able to take it for a test run in liferay-portal and see it work.

**Test plan:**

Update to the new packages:

```sh
yarn add -W --dev ~/code/liferay-frontend-projects/projects/npm-tools/packages/npm-scripts --exact
yarn remove -W liferay-npm-scripts
```

 Producing this lovely diff:

```diff
diff --git a/modules/package.json b/modules/package.json
index 7a4022299b0b..4842b54ca345 100644
--- a/modules/package.json
+++ b/modules/package.json
@@ -1,11 +1,11 @@
 {
 	"devDependencies": {
+		"@liferay/npm-scripts": "/Users/greghurrell/code/liferay-frontend-projects/projects/npm-tools/packages/npm-scripts",
 		"alloy-ui": "^3.1.0-deprecated.40",
 		"babel-plugin-incremental-dom": "3.4.0",
 		"compass-mixins": "0.12.10",
 		"jsdoc": "3.6.3",
 		"liferay-frontend-common-css": "1.0.4",
-		"liferay-npm-scripts": "32.7.0",
 		"metal-jest-serializer": "2.0.0"
 	},
 	"private": true,
diff --git a/modules/yarn.lock b/modules/yarn.lock
index 72947b0643ea..b495195eebf4 100644
--- a/modules/yarn.lock
+++ b/modules/yarn.lock
@@ -1864,6 +1864,108 @@
   dependencies:
     stream "^0.0.2"
 
+"@liferay/eslint-config@21.1.0":
+  version "21.1.0"
+  resolved "https://registry.yarnpkg.com/@liferay/eslint-config/-/eslint-config-21.1.0.tgz#efea4f87ce3f3cef28b54446e92a5a28563474ef"
+  integrity sha512-EC4FyJXL8YHYh8H9KQ9NvA4pEW0UMpkp6NaZSR3/HywIrmxxu9touJv45DRkEt8G0rh8Hr7kCcbSxrEUzOT3kw==
+  dependencies:
+    eslint-config-prettier "^6.5.0"
+    eslint-plugin-no-for-of-loops "^1.0.0"
+    eslint-plugin-no-only-tests "^2.1.0"
+    eslint-plugin-notice "^0.8.9"
+    eslint-plugin-react "^7.18.0"
+    eslint-plugin-react-hooks "^2.2.0"
+    eslint-plugin-sort-destructure-keys "1.3.3"
+
+"@liferay/jest-junit-reporter@1.2.0":
+  version "1.2.0"
+  resolved "https://registry.yarnpkg.com/@liferay/jest-junit-reporter/-/jest-junit-reporter-1.2.0.tgz#120c2df6fc9fd6617af3dfb7fb09cd31e10b6684"
+  integrity sha512-aGZRk6cVtfTvedXXH5r5tWB1EZTuYSrIVpVzDaCTAcoGaW/boDDwGcgIwhcuofhvEasgYu+d1ily8whceGsL/Q==
+  dependencies:
+    strip-ansi "6.0.0"
+    xml "^1.0.1"
+
+"@liferay/npm-bundler-preset-liferay-dev@4.6.2":
+  version "4.6.2"
+  resolved "https://registry.yarnpkg.com/@liferay/npm-bundler-preset-liferay-dev/-/npm-bundler-preset-liferay-dev-4.6.2.tgz#d514846ec1adefe77169bf556bdb2b39fd59c510"
+  integrity sha512-pY9LuTJUJ2yIoZ5emnvBl1xopZ6RH8UacITJIEC+g5WG/kJ0GGt4j5xRG+39O2OYuoKBzPyTaJ2V4KUKgApgEQ==
+  dependencies:
+    babel-preset-liferay-standard "2.19.2"
+    liferay-npm-bundler-loader-css-loader "2.19.2"
+    liferay-npm-bundler-plugin-exclude-imports "2.19.2"
+    liferay-npm-bundler-plugin-inject-imports-dependencies "2.19.2"
+    liferay-npm-bundler-plugin-inject-peer-dependencies "2.19.2"
+    liferay-npm-bundler-plugin-namespace-packages "2.19.2"
+    liferay-npm-bundler-plugin-replace-browser-modules "2.19.2"
+    liferay-npm-bundler-plugin-resolve-linked-dependencies "2.19.2"
+
+"@liferay/npm-scripts@file:../../../liferay-frontend-projects/projects/npm-tools/packages/npm-scripts":
+  version "32.7.0"
+  dependencies:
+    "@babel/cli" "^7.2.3"
+    "@babel/core" "^7.8.3"
+    "@babel/plugin-proposal-class-properties" "7.8.3"
+    "@babel/plugin-proposal-export-namespace-from" "7.8.3"
+    "@babel/plugin-proposal-nullish-coalescing-operator" "7.8.3"
+    "@babel/plugin-proposal-object-rest-spread" "7.8.3"
+    "@babel/plugin-proposal-optional-chaining" "7.9.0"
+    "@babel/preset-env" "^7.4.2"
+    "@babel/preset-react" "7.8.3"
+    "@liferay/eslint-config" "21.1.0"
+    "@liferay/jest-junit-reporter" "1.2.0"
+    "@liferay/npm-bundler-preset-liferay-dev" "4.6.2"
+    "@storybook/addon-a11y" "^5.1.9"
+    "@storybook/addon-actions" "^5.1.9"
+    "@storybook/addon-knobs" "^5.1.9"
+    "@storybook/addon-viewport" "^5.1.9"
+    "@storybook/core" "5.3.3"
+    "@storybook/react" "^5.1.9"
+    "@testing-library/dom" "5.6.1"
+    "@testing-library/jest-dom" "4.0.0"
+    "@testing-library/react" "8.0.7"
+    "@testing-library/react-hooks" "3.4.1"
+    "@testing-library/user-event" "4.2.4"
+    babel-eslint "^10.0.3"
+    babel-jest "^25.1.0"
+    babel-loader "8.0.6"
+    babel-plugin-transform-react-remove-prop-types "0.4.24"
+    cosmiconfig "^6.0.0"
+    cross-env "^7.0.0"
+    cross-spawn "7.0.1"
+    css-loader "^3.0.0"
+    deepmerge "^4.0.0"
+    eslint "6.8.0"
+    fs-extra "^8.1.0"
+    globby "11.0.0"
+    gulp "^4.0.2"
+    html-webpack-plugin "4.3.0"
+    http-proxy-middleware "0.21.0"
+    jest "^25.1.0"
+    jest-environment-jsdom-thirteen "1.0.1"
+    jest-fetch-mock "3.0.1"
+    liferay-lang-key-dev-loader "^1.0.3"
+    liferay-npm-bridge-generator "2.19.2"
+    liferay-npm-bundler "2.19.2"
+    liferay-theme-tasks "10.0.2"
+    metal-tools-soy "4.3.2"
+    mini-css-extract-plugin "0.9.0"
+    minimist "^1.2.0"
+    prettier "2.0.5"
+    react "*"
+    react-dom "*"
+    react-test-renderer "*"
+    regenerator-runtime "0.13.3"
+    resolve "^1.14.2"
+    rimraf "^3.0.2"
+    sass-loader "^8.0.2"
+    script-ext-html-webpack-plugin "2.1.4"
+    style-ext-html-webpack-plugin "4.1.2"
+    style-loader "^1.1.3"
+    stylelint "^13.2.0"
+    webpack "^4.39.1"
+    webpack-cli "^3.3.6"
+    webpack-dev-server "^3.7.2"
+
 "@mdx-js/react@^1.0.0", "@mdx-js/react@^1.5.2":
   version "1.6.1"
   resolved "https://registry.yarnpkg.com/@mdx-js/react/-/react-1.6.1.tgz#46e56602c1f513452db2f1f4185f56dc60a4fcb7"
@@ -8003,19 +8105,6 @@ escodegen@^1.11.0, escodegen@^1.11.1, escodegen@^1.14.1:
   optionalDependencies:
     source-map "~0.6.1"
 
-eslint-config-liferay@21.1.0:
-  version "21.1.0"
-  resolved "https://registry.yarnpkg.com/eslint-config-liferay/-/eslint-config-liferay-21.1.0.tgz#3b0b1405a4e9af1dea94b941930a5e387870b0cc"
-  integrity sha512-zTQpnrn8y5QK7UKqxjgKPjU+wDVdJkSsBRlDAr40jWWVqrII+tR1jAtbtItSCpT4SEt821fd6AYNaBlP8G2Y2w==
-  dependencies:
-    eslint-config-prettier "^6.5.0"
-    eslint-plugin-no-for-of-loops "^1.0.0"
-    eslint-plugin-no-only-tests "^2.1.0"
-    eslint-plugin-notice "^0.8.9"
-    eslint-plugin-react "^7.18.0"
-    eslint-plugin-react-hooks "^2.2.0"
-    eslint-plugin-sort-destructure-keys "1.3.3"
-
 eslint-config-prettier@^6.5.0:
   version "6.7.0"
   resolved "https://registry.yarnpkg.com/eslint-config-prettier/-/eslint-config-prettier-6.7.0.tgz#9a876952e12df2b284adbd3440994bf1f39dfbb9"
@@ -11959,14 +12048,6 @@ liferay-frontend-common-css@1.0.4, liferay-frontend-common-css@^1.0.4:
   resolved "https://registry.yarnpkg.com/liferay-frontend-common-css/-/liferay-frontend-common-css-1.0.4.tgz#e4d73e406020d907c909bcacb2700a52fa1c7f16"
   integrity sha1-5Nc+QGAg2QfJCbyssnAKUvocfxY=
 
-liferay-jest-junit-reporter@1.2.0:
-  version "1.2.0"
-  resolved "https://registry.yarnpkg.com/liferay-jest-junit-reporter/-/liferay-jest-junit-reporter-1.2.0.tgz#5224fcf0d2e8917dc28be9a7694e42723afd2fb2"
-  integrity sha512-CS7CFxpVIfEHwQJw/+L6F8FOg2qBFv+uYzfUsRm7EM5bYVZqHRa5q/BjS0lKxm7dcu0LDg9YuQAesv9qvOa5WQ==
-  dependencies:
-    strip-ansi "6.0.0"
-    xml "^1.0.1"
-
 liferay-lang-key-dev-loader@^1.0.3:
   version "1.0.3"
   resolved "https://registry.yarnpkg.com/liferay-lang-key-dev-loader/-/liferay-lang-key-dev-loader-1.0.3.tgz#d4a1c96e5303e9c3039a475ed680b8df214024f1"
@@ -12070,20 +12151,6 @@ liferay-npm-bundler-plugin-resolve-linked-dependencies@2.19.2:
     read-json-sync "^2.0.1"
     semver "^6.3.0"
 
-liferay-npm-bundler-preset-liferay-dev@4.6.2:
-  version "4.6.2"
-  resolved "https://registry.yarnpkg.com/liferay-npm-bundler-preset-liferay-dev/-/liferay-npm-bundler-preset-liferay-dev-4.6.2.tgz#62786af8c9eeb6515575c11c214f1b9d50f7d575"
-  integrity sha512-6ywH9TkLbgnO9R7IXx8ISnfS4PbQ8Q6FaV6FpuEAFTAPRMWgJbFXhvAu3xnUOATFImGWEG8QDpusBboLhlLF1Q==
-  dependencies:
-    babel-preset-liferay-standard "2.19.2"
-    liferay-npm-bundler-loader-css-loader "2.19.2"
-    liferay-npm-bundler-plugin-exclude-imports "2.19.2"
-    liferay-npm-bundler-plugin-inject-imports-dependencies "2.19.2"
-    liferay-npm-bundler-plugin-inject-peer-dependencies "2.19.2"
-    liferay-npm-bundler-plugin-namespace-packages "2.19.2"
-    liferay-npm-bundler-plugin-replace-browser-modules "2.19.2"
-    liferay-npm-bundler-plugin-resolve-linked-dependencies "2.19.2"
-
 liferay-npm-bundler-preset-standard@2.19.2:
   version "2.19.2"
   resolved "https://registry.yarnpkg.com/liferay-npm-bundler-preset-standard/-/liferay-npm-bundler-preset-standard-2.19.2.tgz#5b470ba7231a2e00a3df820c81f9cfe4c5511228"
@@ -12140,75 +12207,6 @@ liferay-npm-bundler@3.0.0-snapshot.dda6cd1:
     xml-js "^1.6.8"
     yargs "^14.0.0"
 
-liferay-npm-scripts@32.7.0:
-  version "32.7.0"
-  resolved "https://registry.yarnpkg.com/liferay-npm-scripts/-/liferay-npm-scripts-32.7.0.tgz#28adccc947d65ecaca08d7305988197576ebb893"
-  integrity sha512-vTD+05HpJ3v/tXTD+rWWX3zvQA7C3yTfHmuvRhPodOKTFg+v+U0ARU2nsxQkTqog7ZoY/6FASnFhqUeWwzG6tA==
-  dependencies:
-    "@babel/cli" "^7.2.3"
-    "@babel/core" "^7.8.3"
-    "@babel/plugin-proposal-class-properties" "7.8.3"
-    "@babel/plugin-proposal-export-namespace-from" "7.8.3"
-    "@babel/plugin-proposal-nullish-coalescing-operator" "7.8.3"
-    "@babel/plugin-proposal-object-rest-spread" "7.8.3"
-    "@babel/plugin-proposal-optional-chaining" "7.9.0"
-    "@babel/preset-env" "^7.4.2"
-    "@babel/preset-react" "7.8.3"
-    "@storybook/addon-a11y" "^5.1.9"
-    "@storybook/addon-actions" "^5.1.9"
-    "@storybook/addon-knobs" "^5.1.9"
-    "@storybook/addon-viewport" "^5.1.9"
-    "@storybook/core" "5.3.3"
-    "@storybook/react" "^5.1.9"
-    "@testing-library/dom" "5.6.1"
-    "@testing-library/jest-dom" "4.0.0"
-    "@testing-library/react" "8.0.7"
-    "@testing-library/react-hooks" "3.4.1"
-    "@testing-library/user-event" "4.2.4"
-    babel-eslint "^10.0.3"
-    babel-jest "^25.1.0"
-    babel-loader "8.0.6"
-    babel-plugin-transform-react-remove-prop-types "0.4.24"
-    cosmiconfig "^6.0.0"
-    cross-env "^7.0.0"
-    cross-spawn "7.0.1"
-    css-loader "^3.0.0"
-    deepmerge "^4.0.0"
-    eslint "6.8.0"
-    eslint-config-liferay "21.1.0"
-    fs-extra "^8.1.0"
-    globby "11.0.0"
-    gulp "^4.0.2"
-    html-webpack-plugin "4.3.0"
-    http-proxy-middleware "0.21.0"
-    jest "^25.1.0"
-    jest-environment-jsdom-thirteen "1.0.1"
-    jest-fetch-mock "3.0.1"
-    liferay-jest-junit-reporter "1.2.0"
-    liferay-lang-key-dev-loader "^1.0.3"
-    liferay-npm-bridge-generator "2.19.2"
-    liferay-npm-bundler "2.19.2"
-    liferay-npm-bundler-preset-liferay-dev "4.6.2"
-    liferay-theme-tasks "10.0.2"
-    metal-tools-soy "4.3.2"
-    mini-css-extract-plugin "0.9.0"
-    minimist "^1.2.0"
-    prettier "2.0.5"
-    react "*"
-    react-dom "*"
-    react-test-renderer "*"
-    regenerator-runtime "0.13.3"
-    resolve "^1.14.2"
-    rimraf "^3.0.2"
-    sass-loader "^8.0.2"
-    script-ext-html-webpack-plugin "2.1.4"
-    style-ext-html-webpack-plugin "4.1.2"
-    style-loader "^1.1.3"
-    stylelint "^13.2.0"
-    webpack "^4.39.1"
-    webpack-cli "^3.3.6"
-    webpack-dev-server "^3.7.2"
-
 liferay-theme-tasks@10.0.2:
   version "10.0.2"
   resolved "https://registry.yarnpkg.com/liferay-theme-tasks/-/liferay-theme-tasks-10.0.2.tgz#6efcbbd3f402c626ef5b77de8fcd0575c79fdd0d"
```

Now run some tests:

`yarn checkFormat`

> `'Cannot find module acorn-jsx'`

For some reason, v6.4.0 of acorn "wins" and gets hoisted thanks to these deps:

- `@liferay#npm-scripts#jest-environment-jsdom-thirteen#jsdom`
- `frontend-js-recharts#liferay-npm-bundler#acorn`
- `@liferay#npm-scripts#webpack`

Then 7.1.0 gets nested in two places:

- `./node_modules/espree/node_modules/acorn`
- `jest-environment-jsdom`

And Yarn decides to put the sole copy of acorn-jsx alongside one of those:

- `./node_modules/espree/node_modules/acorn-jsx`

So, as a quick fix, add 7.1.0 explicitly at top to force that one to be hoisted instead. The real fix when we roll this out will be to try and update our deps to consolidate on a single version; and only use the other trick as a last result.

Next error:

> `Cannot find module liferay-npm-scripts/src/presets/standard'`

So that means updating the references in liferay-portal itself (there are about 20).

Next:

- ESLint bombs with `Error: liferay-npm-scripts is not installed; please run "ant setup-sdk"` (need to edit top-level `.eslintrc.js`)
- Need to edit `prettirrc.js` as well (it doesn't bomb, it just logs)

Next:

```
{ Error: Failed to load plugin '@liferay/portal' declared in '.eslintrc.js » /Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@liferay/eslint-config/portal.js': Cannot find module '@liferay/eslint-plugin-portal'
```

One of those classic "two versions of eslint active" problem, with only one getting patched.

`yarn why` says there is one version, but i see two (top-level + nested inside npm-scripts), so this is a `yarn add` quirk. One I `rm node_modules` over in monorepo then re-add everything works.

Next:

> `{ Error: Failed to load config "liferay/metal" to extend from.`

So just update the names.

Finally, quite a few errors of the form:

```
/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-compatibility/frontend-compatibility-ie/src/main/resources/META-INF/resources/uint16array.slice.js
  1:1  error  Definition for rule 'liferay/no-arrow' was not found.  liferay/no-arrow
```

which will be fixed by updating the rule names, but there are lots of those so I'll do that tomorrow. At least now I've seen it run and work.

This is the diff of the changes to get it running:

https://gist.github.com/wincent/14a3eef8a838aff11703a13cb25b443c

**Comment by jbalsas** [comment]
myinterestispiqued

**Comment by wincent** [comment]
Ok, I finished testing this on a branch with changes to the `@liferay/npm-scripts` version (runs all tests) and with other changes (runs only on changed files). Going to merge it.

**Pull request merged**
