### PR TITLE
revert: AUI-1947 Fix odd behavior on Autosize iframe

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,
Our customer finds out an issue related to the autosize iframe, this PR is to fix that issue.
The original request is https://issues.liferay.com/browse/LPP-46052 and the PTR is https://issues.liferay.com/browse/PTR-3286
AUI ticket to fix the issue:
https://issues.liferay.com/browse/AUI-3215
Please help me to verify this and leave comments if any.
Thank you very much,
Chi

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
> Dear Team, Our customer finds out an issue related to the autosize iframe, this PR is to fix that issue. The original request is https://issues.liferay.com/browse/LPP-46052 and the PTR is https://issues.liferay.com/browse/PTR-3286 LPS to fix the issue: https://issues.liferay.com/browse/LPS-161586 Please help me to verify this and leave comments if any. Thank you very much, Chi

Hi @chileces,

The PR look good to me, the only thing is that you need to change is:

1. The title to "fix: ..." like in https://github.com/liferay/liferay-frontend-projects/pull/979

2. The commit message should contain an AUI ticket and not LPS, so you need to create a new AUI ticket. The LPS-161586 could be used to update the alloyui version in our portal, see https://github.com/liferay/liferay-portal/pull/4828

After you do the changes you could force push to this pull.

Hope it helps.

Regards.

**Comment by chileces** [comment]
hi @georgel-pop-lr ,
i have updated it according to your request.
Cheers,
Chi

**Comment by georgel-pop-lr** [comment]
Hi @bryceosterhaus,

When you can, please review and if all okay, and when you are available publish a new version.

Thanks for your help.

Regards.

**Comment by bryceosterhaus** [comment]
https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.103/

**Comment by georgel-pop-lr** [comment]
> https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.103/

Thanks, @bryceosterhaus.

@chileces, could you please tests if all works well with this new version published.

If all works well, please send a pull to liferay-portal master under LPS-161586, and once ticket is closed back-port it, till 7.1.x branch.

Regards.

**Comment by chileces** [comment]
Hello @georgel-pop-lr , I've tested it and sent the PR to the Liferay-portal at https://github.com/liferay/liferay-portal/pull/4948
thank you so much,
Chi Le

**Comment by georgel-pop-lr** [comment]
> Hello @georgel-pop-lr , I've tested it and sent the PR to the Liferay-portal at [liferay-frontend/liferay-portal#2678](https://github.com/liferay-frontend/liferay-portal/pull/2678) thank you so much, Chi Le

Hi @chileces,

Sorry I sent you the wrong pull example to liferay user by mistake (we never send to this user in liferay-portal), but I saw you send it to the right user liferay-frontend now.

Regards.

**Pull request merged**
