### PR TITLE
docs(gh-jira-sync): update exalate user mapping adding headless squad

### PR DESCRIPTION
**Pull request by brunofernandezg**
Just updated the user mappings (GH-Jira) in frontend-projects and Clay Jira-Exalate sync scripts.

### CODE REVIEW

**Comment by brunofernandezg** [comment]
At first I was going to wait to fix the problem with issues sync to do those changes, but I think this is an easy change that would be perfect to test the update process for the first time. As soon as is merged I'll open an IS ticket to update the Scripts in Jira.

Although probably headless squad members won't work on Clay repo for now, I think is better to have the same user map for all scripts so it's easier to maintain.

**Review by bryceosterhaus — CHANGES_REQUESTED** [review]
I think there might be some whitespace off here. Take a look at the rendered output
Screen Shot 2021-05-19 at 11 02 58 AM

**Comment by brunofernandezg** [comment]
Thanks @bryceosterhaus, you are right. I didn't realize tabs were coded as four white spaces 🤦
Fixed

**Comment by bryceosterhaus** [comment]
@brunofernandezg github's whitespacing can be atrocious.

Greg better fix this

**Pull request merged**
