### PR TITLE
chore(npm-scripts): update to typescript@4.2.3

### PR DESCRIPTION
**Pull request by wincent**
Seeing as we're sending TS stuff to liferay-portal, may as well take the opportunity to freshen things up.

**Test plan:** `yarn add -W --dev path/to/npm-scripts` in `modules/` and confirm that all TS modules still building and testing (ie. `remote-app-client-js`, `frontend-js-state-web`, and with https://github.com/liferay-frontend/liferay-portal/pull/942 checked out, `frontend-js-react-web`).

### CODE REVIEW

**Comment by wincent** [comment]
As per Frontend Guidelines, I am allowed to ninja-merge as long as I include a ninja-merge GIF.

ninja-merge-5

Am I doing it right?

**Comment by jbalsas** [comment]
> Am I doing it right?

Tell me you have some kind of macro to randomize the ninja gif and keep the message the same 🙏

**Comment by wincent** [comment]
If by "macro" you mean "copy-paste message into four browser tabs then drag image from my famous `~/Pictures/Gifs/` folder (currently populated with 780 MB of beautiful artifacts)", then the answer is yes, I have a macro.

I do have an actual [Alfred](https://www.alfredapp.com/) shortcut to search for gifs and download them into said folder...

one-does-not-simply-get-all-these-gifs

**Comment by jbalsas** [comment]
>If by "macro" you mean "copy-paste message into four browser tabs then drag image from my famous ~/Pictures/Gifs/ folder (currently populated with 780 MB of beautiful artifacts)", then the answer is yes, I have a macro.
>
>I do have an actual Alfred shortcut to search for gifs and download them into said folder...

shutupandtakemymoney

**Pull request merged**
