### PR TITLE
revert(alloy-ui): LPS-160083 calendar event date picker

### PR DESCRIPTION
**Pull request by crodriguezy**
Caused by pull https://github.com/liferay/liferay-frontend-projects/pull/975

This is a temporary solution to fix the regression https://issues.liferay.com/browse/LPS-160083. We should develop a more elaborated one for the original case.

@bryceosterhaus When you can, please review and release a new version. Thanks!

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@crodriguezy can you update the commit messages to follow the conventional commits format? It should look something like

```
revert(alloy-ui): Fix LPS-157062 Calendar event date picker is messy and...
```

**Comment by crodriguezy** [comment]
HI @bryceosterhaus , done :)

**Comment by bryceosterhaus** [comment]
@crodriguezy does this need to be released right away or can we wait for a proper implementation?

**Comment by crodriguezy** [comment]
Hi @bryceosterhaus , could you please release it, please? We'll work ASAP in the full implementation.
Thank you!

**Comment by bryceosterhaus** [comment]
@crodriguezy here ya go, https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.102/

**Comment by crodriguezy** [comment]
Thanks a lot 💯 !

**Pull request merged**
