### PR TITLE
docs(liferay-theme-tasks): Update the readme.md

### PR DESCRIPTION
**Pull request by pat270**
I've updated the `liferay-theme-tasks` readme to include:
- how to revert to using libsass for older themes
- a better link to sassOptions, gulp-sass no longer bundles a Sass compiler with it
- add versions of unstyled and styled themes for 7.4

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
This looks great! Thanks for adding these docs, @pat270!

**Comment by bryceosterhaus** [comment]
Screen Shot 2022-01-20 at 6 01 31 PM
just need an update to this commit name

@pat270

**Comment by izaera** [comment]
:clap:

**Comment by pat270** [comment]
@bryceosterhaus not a problem, what should I change the commit message to?

**Comment by bryceosterhaus** [comment]
@pat270 it was just a typo, `liferay-them-tasks` -> `liferay-theme-tasks`, missing an `e`

**Comment by pat270** [comment]
@bryceosterhaus thanks, maybe I need to increase my browsers font size 👴

**Comment by bryceosterhaus** [comment]
@pat270 I recently had to increase my terminal font. I think I need to go to get my eyes checked 🤓

**Pull request merged**
