### PR TITLE
feat(js-api): labeler test, please ignore

### PR DESCRIPTION
**Pull request by markocikos**
Test, context in https://github.com/liferay/liferay-frontend-projects/pull/1185

### CODE REVIEW

**Comment by markocikos** [comment]
@izaera it works! :tada:

**Comment by izaera** [comment]
> @izaera it works! 🎉

You said we have to ignore this PR... :unamused:

**Comment by markocikos** [comment]
Well, labeler works as expected. I don't know what is this test-windows failure, it doesn't look related :eyes:

**Comment by izaera** [comment]
Windows tests are flaky, usually.

**Pull request closed without merging**
