### PR TITLE
feat(npm-scripts): support .scss files

### PR DESCRIPTION
**Pull request by izaera**
We need this to be able to migrate frontend-taglib-clay, for example. It includes source like:

```javascript
import from './perico.scss';
```

Which was previously handled by the bundler. Now we support it with a webpack loader.

### CODE REVIEW

**Comment by izaera** [comment]
Shouldn't this trigger the CI? :thinking:

**Comment by bryceosterhaus** [comment]
I think github actions took a quick nap

**Comment by izaera** [comment]
So, it's green. Should I merge?

**Comment by bryceosterhaus** [comment]
It looks good to me, feel free to merge

**Pull request merged**
