### PR TITLE
fix(npm-scripts): provide (inactive-by-default) tooling for formatting JS in JSP inside build

### PR DESCRIPTION
**Pull request by wincent**
Just testing the [claim made in this Slack thread](https://liferay.slack.com/archives/C04D8HMEF/p1606323974062700?thread_ts=1606233408.059000&cid=C04D8HMEF) that the reason why my earlier attempts to minify-in-place inside "build/" may have seemed to not be working due to Gradle caching.

While the cache may cause problems, I am skeptical that this will work because in my testing I found that `processResources` happens too late (after `npm-scripts` runs), but in the interests of thoroughness I am going to try this out and test it in a full `ant all` run anyway.

---

Final summary: we tested this out and the minify-in-`build/` trick does work, but even with minification turned way down to avoid reordering issues, testing in DXP shows that it is too risky to turn on by default (for example, we see other parts of the toolchain choking as a result of tags + lines following each other on the same line — probably something we could work around with some careful semicolon insertion, but it would be very fiddly...). So last commit in this PR gates the functionality behind an environment variable which will be empty by default.

### CODE REVIEW

**Comment by wincent** [comment]
Happily, this looks like it is going to work _and_ additionally it uncovered a latent bug as seen [in this diff](https://gist.github.com/wincent/9c98f3d77fcca8a3753e680137f5f3a8).

You can see that the minifier is freely reordering stuff which means that some of our JSP syntax substitutions get restored into the wrong "slots" after minification.

For example, `data = Liferay.Util.ns('_<%= HtmlUtil.escapeJS(portletResource) %>_', data)` gets restored as `(data = Liferay.Util.ns('_<portlet:namespace />_', data))`; and the corresponding inverse error is `<portlet:namespace />resetPreview` getting restored as `<%= HtmlUtil.escapeJS(portletResource) %>resetPreview`.

So I'm going to turn the minification waaaay down for JSP so that it is basically only whitespace changes (it already was dialled way down, but I didn't anticipate that it would make this kind of reordering), add a regression test, and retry.

**Comment by wincent** [comment]
Will obviously need to rebase and drop the pre-release commit(s) before calling this one final.

**Comment by jbalsas** [comment]
> You can see that the minifier is freely reordering stuff which means that some of our JSP syntax substitutions get restored into the wrong "slots" after minification.

didntseethatcoming

**Comment by wincent** [comment]
Ok, based on testing [over in my fork](https://github.com/wincent/liferay-portal/pull/371), I am "de-fanging" this by turning it off by default. We can look at turning it on later if we feel brave, but for now it remains a harmless no-op. Taking it out of draft.

**Comment by jbalsas** [comment]
finishline

**Pull request merged**
