### PR TITLE
fix(npm-scripts): temporary work around for grabbing rules config at both the root and module level

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This is temporary until we provide a full solution in https://issues.liferay.com/browse/LPS-172749

### CODE REVIEW

**Comment by izaera** [comment]
:scream:

**Comment by izaera** [comment]
I've relaunched the windows test, since it looks like it could be valid :shrug:

**Comment by izaera** [comment]
It passed the test :+1:

**Comment by bryceosterhaus** [comment]
The windows failure was due to a async timeout. I've seen it happen before, I think it may have to just do with the machine on github actions, so I figured it would be fine to merge. Plus I like to live dangerously

**Comment by izaera** [comment]
YOLO

**Pull request merged**
