### PR TITLE
refactor(js-toolkit): make tests work in monorepo

### PR DESCRIPTION
**Pull request by wincent**
This makes the tests (and therefore the build) of the two js-toolkit projects work in the monorepo. This was very fiddly and a bit like whack-a-mole, so you can see some of the things I had to try in the commit messages — not the cleanest history I've ever produced; sorry for that.

Some of the key things that are going on:

- Many `devDependencies` hoisted and/or updated in order to get things working (I tried to touch as little as possible, to make this as minimal and safe as I could, but I ended up having to touch more than I would have liked).
- Adjusting GitHub actions to do build and test instead of just test, and running the v2 js-toolkit tests as a separate job because they live outside of the main set of workspaces.
- Tweaking `.eslintignore` and `.prettierignore` to reflect build artifacts that are there now that the build is working.
- Because of package versions for TypeScript-related stuff, as well as the new structure here, had to tweak the tsconfig.json files a bit to avoid errors.

### CODE REVIEW

**Comment by wincent** [comment]
Just force-pushed with a bunch of wrangling on top. I think this one has at least a reasonable chance of working — 😂. Enough to take it out of draft mode at least. Sorry for the messy pull.

**Comment by wincent** [comment]
Woot! Of the three test jobs, [the main one](https://github.com/liferay/liferay-frontend-projects/pull/133/checks?check_run_id=1220537566) passes. Going to see if I can fix the [Windows](https://github.com/liferay/liferay-frontend-projects/pull/133/checks?check_run_id=1220537852) and [v2 js-toolkit jobs](https://github.com/liferay/liferay-frontend-projects/pull/133/checks?check_run_id=1220537713) now.

**Comment by wincent** [comment]
Made some progress! Tests now [actually run on Windows](https://github.com/liferay/liferay-frontend-projects/pull/133/checks?check_run_id=1221124885), with some failure that looks expected because we've never run them on Windows before:

```
FAIL projects/js-toolkit/packages/liferay-js-toolkit-core/src/file/__tests__/FilePath.test.ts
  ● in posix systems › toDotRelative works

    expect(received).toEqual(expected) // deep equality

    Expected: "./a/path"
    Received: "./a\\path"

      41 | 	it('toDotRelative works', () => {
      42 | 		expect(new FilePath('').toDotRelative().asNative).toEqual('.');
    > 43 | 		expect(new FilePath('a/path').toDotRelative().asNative).toEqual(
         | 		                                                        ^
      44 | 			'./a/path'
      45 | 		);
      46 | 

      at Object.<anonymous> (packages/liferay-js-toolkit-core/src/file/__tests__/FilePath.test.ts:43:59)
```

**Comment by jbalsas** [comment]
> Made some progress! Tests now actually run on Windows, with some failure that looks expected because we've never run them on Windows before:

Getting closer!! 💪

**Comment by wincent** [comment]
Ok, so going to merge this even though it is a bit messy. Next steps should be cleaner than this!

**Pull request merged**
