### PR TITLE
fix(alloy-ui): Wrong date in case the year format is four digit but the value is two digit

### PR DESCRIPTION
**Pull request by rolandpakai**
This is a PR for fixing the following issue: 
https://github.com/liferay/liferay-frontend-projects/issues/879

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @bryceosterhaus 

could you please review my PR?

Thanks, Roland

**Comment by bryceosterhaus** [comment]
@rolandpakai sorry for the delay, I just got back into the office. 

Thanks for sending this, do you also need an immediate release of alloy for this?

**Comment by rolandpakai** [comment]
Hi @bryceosterhaus 

yes, it will be nice to have a new release with the fix because we have a depending cutomer issue in Liferay. 

Thanks, Roland

**Comment by bryceosterhaus** [comment]
@rolandpakai, sounds good. I will get one cut and released either today or tomorrow, I will let you know when it is cut.

**Comment by bryceosterhaus** [comment]
@rolandpakai I just released a new version at 

[Github](https://github.com/liferay/liferay-frontend-projects/releases/tag/alloy-ui%2Fv3.1.0-deprecated.91)

[Maven](https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.91/)

**Comment by rolandpakai** [comment]
Thank you @bryceosterhaus

**Pull request merged**
