### PR TITLE
fix(npm-scripts): honor NODE_ENV setting when invoking webpack

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Oops, lint failed. We should find a way to make our selection processes better... :roll_eyes:

**Comment by bryceosterhaus** [comment]
LGTM

>  We should find a way to make our selection processes better

Not entirely sure what you mean by "selection processes" here

**Comment by izaera** [comment]
> Not entirely sure what you mean by "selection processes" here

The process of selecting who enters (in this case me) the Company and who doesn't... :smiling_face_with_tear:

**Pull request merged**
